<?php

namespace AppBundle\Repository;

/**
 * PitchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PitchRepository extends \Doctrine\ORM\EntityRepository
{
}
